title: Atom Studios
email: info@atomstudios.fr
description:
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
